"""
Page table for report_generator.py: title, parent, menu order and folder of
every pool, subpool and flow page in the documentation portal. For pool and
subpool pages, intro is the fixed text above the MANUAL block, with
{BALANCE} where the mass-balance plot for the code in balance is inserted.
The page text itself is edited in the .md files, not here.
"""
PAGES = [{'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_AT_AT_Emissions_N2O.md',
  'title': 'Energy conversion emissions (N2O)',
  'nav_order': 1,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_AT_AT_Emissions_NOx.md',
  'title': 'Energy conversion emissions (NOx)',
  'nav_order': 2,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_EF_IC_Fuel_for_industry_Nmix.md',
  'title': 'Fuel for industry',
  'nav_order': 3,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_EF_OE_Fuel_for_heating_Nmix.md',
  'title': 'Fuel for heating',
  'nav_order': 4,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_EF_TR_Fuel_for_transport_Nmix.md',
  'title': 'Fuel for transport',
  'nav_order': 5,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_MP_OP_Fuel_used_as_feedstock_Nmix.md',
  'title': 'Fuel used as feedstock',
  'nav_order': 6,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_EC_RW_RW_Fuel_export_Nmix.md',
  'title': 'Fuel export',
  'nav_order': 7,
  'parent': 'Energy conversion (EF.EC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_IC_AT_AT_Emissions_N2O.md',
  'title': 'Industrial emissions (N2O)',
  'nav_order': 1,
  'parent': 'Manufacturing industries and construction (EF.IC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_IC_AT_AT_Emissions_NH3.md',
  'title': 'Industrial emissions (NH3)',
  'nav_order': 2,
  'parent': 'Manufacturing industries and construction (EF.IC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_IC_AT_AT_Emissions_NOx.md',
  'title': 'Industrial emissions (NOx)',
  'nav_order': 3,
  'parent': 'Manufacturing industries and construction (EF.IC)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_OE_AT_AT_Emissions_N2O.md',
  'title': 'Other energy emissions (N2O)',
  'nav_order': 1,
  'parent': 'Other energy and fuels (EF.OE)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_OE_AT_AT_Emissions_NH3.md',
  'title': 'Other energy emissions (NH3)',
  'nav_order': 2,
  'parent': 'Other energy and fuels (EF.OE)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_OE_AT_AT_Emissions_NOx.md',
  'title': 'Other energy emissions (NOx)',
  'nav_order': 3,
  'parent': 'Other energy and fuels (EF.OE)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_TR_AT_AT_Emissions_N2O.md',
  'title': 'Transport emissions (N2O)',
  'nav_order': 1,
  'parent': 'Transportation (EF.TR)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_TR_AT_AT_Emissions_NH3.md',
  'title': 'Transport emissions (NH3)',
  'nav_order': 2,
  'parent': 'Transportation (EF.TR)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_TR_AT_AT_Emissions_NOx.md',
  'title': 'Transport emissions (NOx)',
  'nav_order': 3,
  'parent': 'Transportation (EF.TR)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'flow_EF_TR_RW_RW_Export_of_transport_fuels_Nmix.md',
  'title': 'Export of transport fuels',
  'nav_order': 4,
  'parent': 'Transportation (EF.TR)',
  'kind': 'flow'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'pool_energy_and_fuels.md',
  'title': '1. Energy and fuels (EF)',
  'nav_order': 2,
  'has_children': True,
  'kind': 'pool',
  'balance': 'EF',
  'intro': '# Pool: 1. Energy and fuels (EF)\n'
           '\n'
           'This pool is divided into four operational sub-pools. Explore them using the side menu or links below:\n'
           '\n'
           '* [Energy conversion (EF.EC)](subpool_energy_conversion.html)\n'
           '* [Manufacturing industries and construction (EF.IC)](subpool_industry.html)\n'
           '* [Transportation (EF.TR)](subpool_transport.html)\n'
           '* [Other energy and fuels (EF.OE)](subpool_other_energy.html)\n'
           '\n'
           '{BALANCE}\n'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'subpool_energy_conversion.md',
  'title': 'Energy conversion (EF.EC)',
  'nav_order': 1,
  'parent': '1. Energy and fuels (EF)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'EF.EC',
  'intro': '# Subpool: Energy conversion (EF.EC)\n\n{BALANCE}'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'subpool_industry.md',
  'title': 'Manufacturing industries and construction (EF.IC)',
  'nav_order': 2,
  'parent': '1. Energy and fuels (EF)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'EF.IC',
  'intro': '# Subpool: Manufacturing industries and construction (EF.IC)\n\n{BALANCE}'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'subpool_other_energy.md',
  'title': 'Other energy and fuels (EF.OE)',
  'nav_order': 4,
  'parent': '1. Energy and fuels (EF)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'EF.OE',
  'intro': '# Subpool: Other energy and fuels (EF.OE)\n\n{BALANCE}'},
 {'folder': 'energy_and_fuels_pool',
  'file': 'subpool_transport.md',
  'title': 'Transportation (EF.TR)',
  'nav_order': 3,
  'parent': '1. Energy and fuels (EF)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'EF.TR',
  'intro': '# Subpool: Transportation (EF.TR)\n\n{BALANCE}'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_AG_MM_Farm_animal_feed_Nmix.md',
  'title': 'Farm Animal Feed',
  'nav_order': 1,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_AG_SM_Seeds_and_planting_material__Nmix.md',
  'title': 'Seeds and Planting Material',
  'nav_order': 2,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_HS_HS_Food_products_Nmix.md',
  'title': 'Food Products to Consumers',
  'nav_order': 3,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_HY_AC_Feed_to_coastal_aquaculture_Nmix.md',
  'title': 'Feed to Coastal Aquaculture',
  'nav_order': 4,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_HY_SW_Untreated_wastewater_Nmix.md',
  'title': 'Untreated Wastewater (Food Industry)',
  'nav_order': 5,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_PR_SO_Food_industry_waste_Nmix.md',
  'title': 'Food Industry Waste',
  'nav_order': 6,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_PR_WW_Food_industry_wastewater_Nmix.md',
  'title': 'Food Industry Wastewater',
  'nav_order': 7,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_RW_RW_Feed_export_Nmix.md',
  'title': 'Feed Export',
  'nav_order': 8,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_FP_RW_RW_Food_export_Nmix.md',
  'title': 'Food Export',
  'nav_order': 9,
  'parent': 'Food and Feed Processing (MP.FP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_AG_SM_Mineral_fertilizer_Nmix.md',
  'title': 'Mineral Fertilizer for Agriculture',
  'nav_order': 1,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_AT_AT_Emissions_N2O.md',
  'title': 'Industrial Emissions (N2O)',
  'nav_order': 2,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_AT_AT_Emissions_NH3.md',
  'title': 'Industrial Emissions (NH3)',
  'nav_order': 3,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_AT_AT_Emissions_NOx.md',
  'title': 'Industrial Emissions (NOx)',
  'nav_order': 4,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_EF_IC_Industrial_waste_fuels_Nmix.md',
  'title': 'Industrial Waste Fuels',
  'nav_order': 5,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_FS_FO_Mineral_fertilizer_Nmix.md',
  'title': 'Mineral Fertilizer for Forestry',
  'nav_order': 6,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_HS_HS_Consumer_goods_Nmix.md',
  'title': 'Consumer Goods (Mass Balance)',
  'nav_order': 7,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_HS_HS_Mineral_fertilizer_Nmix.md',
  'title': 'Mineral Fertilizer for HS',
  'nav_order': 8,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_HY_SW_Untreated_wastewater_Nmix.md',
  'title': 'Untreated Wastewater (Other Industry)',
  'nav_order': 9,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_PR_SO_Other_industry_waste_Nmix.md',
  'title': 'Other Industry Waste',
  'nav_order': 10,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_PR_WW_Other_industry_wastewater_Nmix.md',
  'title': 'Other Industry Wastewater',
  'nav_order': 11,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_RW_RW_Mineral_fertilizer_export_Nmix.md',
  'title': 'Mineral Fertilizer Export',
  'nav_order': 12,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'flow_MP_OP_RW_RW_Other_goods_export_Nmix.md',
  'title': 'Other Goods Export',
  'nav_order': 13,
  'parent': 'Other Producing Industry (MP.OP)',
  'kind': 'flow'},
 {'folder': 'materials_and_products_pool',
  'file': 'pool_materials_and_products.md',
  'title': '2. Materials and products (MP)',
  'nav_order': 3,
  'has_children': True,
  'kind': 'pool',
  'balance': 'MP',
  'intro': '# Pool: 2. Materials and products in industry (MP)\n'
           '\n'
           'This pool covers chemical, processing, food, and manufacturing industries in Norway, split into two '
           'primary segments:\n'
           '\n'
           '* [Food and Feed Processing (MP.FP)](subpool_food_and_feed.html)\n'
           '* [Other Producing Industry (MP.OP)](subpool_other_industry.html)\n'
           '{BALANCE}'},
 {'folder': 'materials_and_products_pool',
  'file': 'subpool_food_and_feed.md',
  'title': 'Food and Feed Processing (MP.FP)',
  'nav_order': 1,
  'parent': '2. Materials and products (MP)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'MP.FP',
  'intro': '# Subpool: Food and feed processing (MP.FP)\n\n{BALANCE}\n'},
 {'folder': 'materials_and_products_pool',
  'file': 'subpool_other_industry.md',
  'title': 'Other Producing Industry (MP.OP)',
  'nav_order': 2,
  'parent': '2. Materials and products (MP)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'MP.OP',
  'intro': '# Subpool: Other producing industry (MP.OP)\n\n{BALANCE}\n'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_AG_SM_Manure_application_Nmix.md',
  'title': 'Manure Application',
  'nav_order': 1,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_AT_AT_Emissions_N2O.md',
  'title': 'Manure Emissions (N2O)',
  'nav_order': 2,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_AT_AT_Emissions_NH3.md',
  'title': 'Manure Emissions (NH3)',
  'nav_order': 3,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_AT_AT_Emissions_NOx.md',
  'title': 'Manure Emissions (NOx)',
  'nav_order': 4,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_HY_SW_Leaching_Nmix.md',
  'title': 'Manure Leaching',
  'nav_order': 5,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_MP_FP_Animal_products_Nmix.md',
  'title': 'Animal Products',
  'nav_order': 6,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_MP_OP_Non_edible_animal_products_Nmix.md',
  'title': 'Non-edible Animal Products',
  'nav_order': 7,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_RW_RW_Live_animal_export_Nmix.md',
  'title': 'Live Animal Export',
  'nav_order': 8,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_MM_FS_OL_Manure_from_grazing_on_unmanaged_land_Nmix.md',
  'title': 'Manure from Grazing on Unmanaged Land',
  'nav_order': 9,
  'parent': 'Manure Management (AG.MM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_AG_MM_Fodder_crops_Nmix.md',
  'title': 'Fodder Crops Production',
  'nav_order': 1,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_AT_AT_Emissions_N2.md',
  'title': 'N2 emissions from denitrification',
  'nav_order': 2,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_AT_AT_Emissions_N2O.md',
  'title': 'N2O emissions from denitrification',
  'nav_order': 3,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_AT_AT_Emissions_NH3.md',
  'title': 'NH3 emissions',
  'nav_order': 4,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_AT_AT_Emissions_NOx.md',
  'title': 'NOx emissions from soil management',
  'nav_order': 5,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_HY_SW_Leaching_Nmix.md',
  'title': 'Leaching from soil management',
  'nav_order': 6,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_MP_FP_Food_crop_products_Nmix.md',
  'title': 'Food crop products',
  'nav_order': 7,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'flow_AG_SM_MP_OP_Crop_products_for_industrial_use_Nmix.md',
  'title': 'Crop products for industrial use',
  'nav_order': 8,
  'parent': 'Soil Management (AG.SM)',
  'kind': 'flow'},
 {'folder': 'agriculture_pool',
  'file': 'pool_agriculture.md',
  'title': '3. Agriculture (AG)',
  'nav_order': 4,
  'has_children': True,
  'kind': 'pool',
  'balance': 'AG',
  'intro': '# Pool: 3. Agriculture (AG)\n'
           '\n'
           'This pool is divided into two operational sub-pools. Explore them using the side menu or links below:\n'
           '\n'
           '* [Manure Management (AG.MM)](subpool_manure_management.html)\n'
           '* [Soil Management (AG.SM)](subpool_soil_management.html)\n'
           '{BALANCE}\n'},
 {'folder': 'agriculture_pool',
  'file': 'subpool_manure_management.md',
  'title': 'Manure Management (AG.MM)',
  'nav_order': 1,
  'parent': '3. Agriculture (AG)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'AG.MM',
  'intro': '# Subpool: Manure management, storage and animal husbandry (AG.MM)\n\n{BALANCE}\n'},
 {'folder': 'agriculture_pool',
  'file': 'subpool_soil_management.md',
  'title': 'Soil Management (AG.SM)',
  'nav_order': 2,
  'parent': '3. Agriculture (AG)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'AG.SM',
  'intro': '# Subpool: Soil management (AG.SM)\n\n{BALANCE}\n'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_FO_AT_AT_Emissions_N2.md',
  'title': 'Forest Emissions (N2)',
  'nav_order': 1,
  'parent': 'Forests (FS.FO)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_FO_AT_AT_Emissions_N2O.md',
  'title': 'Forest Emissions (N2O)',
  'nav_order': 2,
  'parent': 'Forests (FS.FO)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_FO_EF_OE_Fuel_wood_for_households_Nmix.md',
  'title': 'Fuel Wood for Households',
  'nav_order': 3,
  'parent': 'Forests (FS.FO)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_FO_HY_SW_Leaching_Nmix.md',
  'title': 'Forest Leaching',
  'nav_order': 4,
  'parent': 'Forests (FS.FO)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_FO_MP_OP_Industrial_round_wood_Nmix.md',
  'title': 'Industrial Round Wood',
  'nav_order': 5,
  'parent': 'Forests (FS.FO)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_OL_AG_MM_Grazing_Nmix.md',
  'title': 'Grazing on Unmanaged Land',
  'nav_order': 1,
  'parent': 'Other Land (FS.OL)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_OL_HY_SW_Leaching_Nmix.md',
  'title': 'Other Land Leaching',
  'nav_order': 2,
  'parent': 'Other Land (FS.OL)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_OL_AT_AT_Emissions_NH3.md',
  'title': 'Other Land Emissions (NH3)',
  'nav_order': 3,
  'parent': 'Other Land (FS.OL)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_OL_AT_AT_Emissions_NOx.md',
  'title': 'Other Land Emissions (NOx)',
  'nav_order': 4,
  'parent': 'Other Land (FS.OL)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'flow_FS_OL_AT_AT_Emissions_N2O.md',
  'title': 'Other Land Emissions (N2O)',
  'nav_order': 5,
  'parent': 'Other Land (FS.OL)',
  'kind': 'flow'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'pool_forests_and_semi_natural.md',
  'title': '4. Forests and semi-natural vegetation (FS)',
  'nav_order': 5,
  'has_children': True,
  'kind': 'pool',
  'balance': 'FS',
  'intro': '# Pool: 4. Forests and semi-natural vegetation (FS)\n'
           '\n'
           'This pool is divided into two operational sub-pools. Explore them using the side menu or links below:\n'
           '\n'
           '* [Forests (FS.FO)](subpool_forests.html)\n'
           '* [Other Land (FS.OL)](subpool_other_land.html)\n'
           '{BALANCE}\n'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'subpool_forests.md',
  'title': 'Forests (FS.FO)',
  'nav_order': 1,
  'parent': '4. Forests and semi-natural vegetation (FS)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'FS.FO',
  'intro': '# Subpool: Forests (FS.FO)\n\n{BALANCE}\n'},
 {'folder': 'forests_and_semi_natural_pool',
  'file': 'subpool_other_land.md',
  'title': 'Other Land (FS.OL)',
  'nav_order': 2,
  'parent': '4. Forests and semi-natural vegetation (FS)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'FS.OL',
  'intro': '# Subpool: Other land (FS.OL)\n\n{BALANCE}\n'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_AG_SM_Biologically_treated_organic_waste_Nmix.md',
  'title': 'Biologically treated organic waste to Ag',
  'nav_order': 1,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_AT_AT_Emissions_N2O.md',
  'title': 'N2O Emissions (Solid Waste)',
  'nav_order': 2,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_AT_AT_Emissions_NH3.md',
  'title': 'NH3 Emissions (Solid Waste)',
  'nav_order': 3,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_AT_AT_Emissions_NOx.md',
  'title': 'NOx Emissions (Solid Waste)',
  'nav_order': 4,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_EF_EC_Waste_to_energy_Nmix.md',
  'title': 'Waste to energy (Incineration)',
  'nav_order': 5,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_HS_HS_Biologically_treated_organic_waste_Nmix.md',
  'title': 'Biologically treated organic waste to HS',
  'nav_order': 6,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_HY_SW_Leaching_Nmix.md',
  'title': 'Leaching from Landfills',
  'nav_order': 7,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_MP_OP_Recycling_Nmix.md',
  'title': 'Material Recycling',
  'nav_order': 8,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_PR_WW_Wastewater_from_landfills_Nmix.md',
  'title': 'Wastewater from Landfills',
  'nav_order': 9,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_RW_RW_Export_for_recycling_Nmix.md',
  'title': 'Export for Recycling',
  'nav_order': 10,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_RW_RW_Export_for_reuse_Nmix.md',
  'title': 'Export for Reuse',
  'nav_order': 11,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_SO_RW_RW_Solid_waste_export_Nmix.md',
  'title': 'Solid Waste Export',
  'nav_order': 12,
  'parent': 'Solid Waste (PR.SO)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_AG_SM_Sewage_sludge_fertilizer_Nmix.md',
  'title': 'Sewage Sludge Fertilizer to Ag',
  'nav_order': 1,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_AT_AT_Emissions_N2.md',
  'title': 'N2 Emissions (Wastewater)',
  'nav_order': 2,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_AT_AT_Emissions_N2O.md',
  'title': 'N2O Emissions (Wastewater)',
  'nav_order': 3,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_HS_HS_Sewage_sludge_fertilizer_Nmix.md',
  'title': 'Sewage Sludge Fertilizer to HS',
  'nav_order': 4,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_HY_CW_Treated_wastewater_discharge_Nmix.md',
  'title': 'Treated Wastewater Discharge to CW',
  'nav_order': 5,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'flow_PR_WW_PR_SO_Sewage_sludge_landfill_Nmix.md',
  'title': 'Sewage Sludge to Landfill',
  'nav_order': 6,
  'parent': 'Wastewater (PR.WW)',
  'kind': 'flow'},
 {'folder': 'processing_of_residues_pool',
  'file': 'pool_processing_of_residues.md',
  'title': '5. Processing of residues (PR)',
  'nav_order': 6,
  'has_children': True,
  'kind': 'pool',
  'balance': 'PR',
  'intro': '# Pool: 5. Processing of residues (PR)\n'
           '\n'
           'This pool is divided into two operational sub-pools. Explore them using the side menu or links below:\n'
           '\n'
           '* [Solid Waste (PR.SO)](subpool_solid_waste.html)\n'
           '* [Wastewater (PR.WW)](subpool_wastewater.html)\n'
           '\n'
           '{BALANCE}\n'},
 {'folder': 'processing_of_residues_pool',
  'file': 'subpool_solid_waste.md',
  'title': 'Solid Waste (PR.SO)',
  'nav_order': 1,
  'parent': '5. Processing of residues (PR)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'PR.SO',
  'intro': '# Subpool: Solid Waste (PR.SO)\n\n{BALANCE}\n'},
 {'folder': 'processing_of_residues_pool',
  'file': 'subpool_wastewater.md',
  'title': 'Wastewater (PR.WW)',
  'nav_order': 2,
  'parent': '5. Processing of residues (PR)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'PR.WW',
  'intro': '# Subpool: Wastewater (PR.WW)\n\n{BALANCE}\n'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'flow_HS_HS_AT_AT_Emissions_NH3.md',
  'title': 'Ammonia Body Emissions',
  'nav_order': 1,
  'parent': '6. Humans and settlements (HS)',
  'kind': 'flow'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'flow_HS_HS_AT_AT_LUC_emissions_N2O.md',
  'title': 'LUC Emissions (N2O)',
  'nav_order': 2,
  'parent': '6. Humans and settlements (HS)',
  'kind': 'flow'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'flow_HS_HS_HY_SW_Overland_flow_Nmix.md',
  'title': 'Urban Overland Flow',
  'nav_order': 3,
  'parent': '6. Humans and settlements (HS)',
  'kind': 'flow'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'flow_HS_HS_PR_SO_Household_waste_Nmix.md',
  'title': 'Household and Settlement Waste',
  'nav_order': 4,
  'parent': '6. Humans and settlements (HS)',
  'kind': 'flow'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'flow_HS_HS_PR_WW_Municipal_wastewater_Nmix.md',
  'title': 'Municipal Wastewater',
  'nav_order': 5,
  'parent': '6. Humans and settlements (HS)',
  'kind': 'flow'},
 {'folder': 'humans_and_settlements_pool',
  'file': 'pool_humans_and_settlements.md',
  'title': '6. Humans and settlements (HS)',
  'nav_order': 7,
  'has_children': True,
  'kind': 'pool',
  'balance': 'HS',
  'intro': '# Pool: 6. Humans and settlements (HS)\n\n{BALANCE}\n'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_AG_SM_Biological_N2_fixation_N2.md',
  'title': 'Biological N2 Fixation (Agricultural Soils)',
  'nav_order': 1,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_AG_SM_Deposition_OXN.md',
  'title': 'Oxidized N Deposition (Agricultural Soils)',
  'nav_order': 2,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_AG_SM_Deposition_RDN.md',
  'title': 'Reduced N Deposition (Agricultural Soils)',
  'nav_order': 3,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_FO_Deposition_OXN.md',
  'title': 'Oxidized N Deposition (Forest)',
  'nav_order': 4,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_FO_Deposition_RDN.md',
  'title': 'Reduced N Deposition (Forest)',
  'nav_order': 5,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_FO_N2_fixation_N2.md',
  'title': 'Biological N2 Fixation (Forest)',
  'nav_order': 6,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_OL_Deposition_OXN.md',
  'title': 'Oxidized N Deposition (Other Land)',
  'nav_order': 7,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_OL_Deposition_RDN.md',
  'title': 'Reduced N Deposition (Other Land)',
  'nav_order': 8,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_FS_OL_N2_fixation_N2.md',
  'title': 'Biological N2 Fixation (Other Land)',
  'nav_order': 9,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_HS_HS_Deposition_OXN.md',
  'title': 'Oxidized N Deposition (Settlements)',
  'nav_order': 10,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_HS_HS_Deposition_RDN.md',
  'title': 'Reduced N Deposition (Settlements)',
  'nav_order': 11,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_HY_SW_Deposition_OXN.md',
  'title': 'Oxidized N Deposition (Surface Water)',
  'nav_order': 12,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_HY_SW_Deposition_RDN.md',
  'title': 'Reduced N Deposition (Surface Water)',
  'nav_order': 13,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_HY_SW_N2_fixation_N2.md',
  'title': 'Biological N2 Fixation (Surface Water)',
  'nav_order': 14,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_MP_OP_Ammonia_synthesis_N2_fixation_N2.md',
  'title': 'Ammonia Synthesis N2 Fixation',
  'nav_order': 15,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_RW_RW_Atmospheric_outflow_OXN.md',
  'title': 'Atmospheric Outflow (Oxidized N)',
  'nav_order': 16,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'flow_AT_AT_RW_RW_Atmospheric_outflow_RDN.md',
  'title': 'Atmospheric Outflow (Reduced N)',
  'nav_order': 17,
  'parent': '7. Atmosphere (AT)',
  'kind': 'flow'},
 {'folder': 'atmosphere_pool',
  'file': 'pool_atmosphere.md',
  'title': '7. Atmosphere (AT)',
  'nav_order': 8,
  'has_children': True,
  'kind': 'pool',
  'balance': 'AT',
  'intro': '# Pool: 7. Atmosphere (AT)\n'
           '\n'
           'This section contains all documented nitrogen flows leaving the Atmosphere pool.\n'
           '{BALANCE}\n'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_AC_HY_CW_Excretia_Nmix.md',
  'title': 'Excretia',
  'nav_order': 1,
  'parent': 'Aquaculture (HY.AC)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_AC_HY_CW_Waste_feed_Nmix.md',
  'title': 'Waste feed',
  'nav_order': 2,
  'parent': 'Aquaculture (HY.AC)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_AC_MP_FP_Coastal_fish_and_seafood_Nmix.md',
  'title': 'Aquaculture production',
  'nav_order': 3,
  'parent': 'Aquaculture (HY.AC)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_CW_MP_FP_Fish_(wild_catch)_Nmix.md',
  'title': 'Wild fish catch',
  'nav_order': 1,
  'parent': 'Coastal Water (HY.CW)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_CW_MP_FP_Shellfish_Nmix.md',
  'title': 'Shellfish',
  'nav_order': 2,
  'parent': 'Coastal Water (HY.CW)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_SW_AT_AT_Emissions_N2.md',
  'title': 'N2 emissions from denitrification in surface waters',
  'nav_order': 1,
  'parent': 'Surface Water (HY.SW)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_SW_AT_AT_Emissions_N2O.md',
  'title': 'Surface water N2O emissions',
  'nav_order': 2,
  'parent': 'Surface Water (HY.SW)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'flow_HY_SW_HY_CW_Inflow_to_coastal_waters_Nmix.md',
  'title': 'Inflow to coastal waters',
  'nav_order': 3,
  'parent': 'Surface Water (HY.SW)',
  'kind': 'flow'},
 {'folder': 'hydrosphere_pool',
  'file': 'pool_hydrosphere.md',
  'title': '8. Hydrosphere (HY)',
  'nav_order': 9,
  'has_children': True,
  'kind': 'pool',
  'balance': 'HY',
  'intro': '# Pool: 8. Hydrosphere (HY)\n'
           '\n'
           'The hydrosphere ecosystem is split into three operational modules. Explore them below:\n'
           '\n'
           '* [Surface Water (HY.SW)](subpool_surface_water.html)\n'
           '* [Coastal Water (HY.CW)](subpool_coastal_water.html)\n'
           '* [Aquaculture (HY.AC)](subpool_aquaculture.html)\n'
           '{BALANCE}\n'},
 {'folder': 'hydrosphere_pool',
  'file': 'subpool_aquaculture.md',
  'title': 'Aquaculture (HY.AC)',
  'nav_order': 3,
  'parent': '8. Hydrosphere (HY)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'HY.AC',
  'intro': '# Subpool: Aquaculture (HY.AC)\n\n{BALANCE}\n'},
 {'folder': 'hydrosphere_pool',
  'file': 'subpool_coastal_water.md',
  'title': 'Coastal Water (HY.CW)',
  'nav_order': 2,
  'parent': '8. Hydrosphere (HY)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'HY.CW',
  'intro': '# Subpool: Coastal water (HY.CW)\n\n{BALANCE}\n'},
 {'folder': 'hydrosphere_pool',
  'file': 'subpool_surface_water.md',
  'title': 'Surface Water (HY.SW)',
  'nav_order': 1,
  'parent': '8. Hydrosphere (HY)',
  'has_children': True,
  'kind': 'subpool',
  'balance': 'HY.SW',
  'intro': '# Subpool: Surface water (HY.SW)\n\n{BALANCE}\n'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_AG_MM_Animal_feed_import_Nmix.md',
  'title': 'Animal Feed Import',
  'nav_order': 1,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_AG_MM_Live_animal_import_Nmix.md',
  'title': 'Live Animal Import',
  'nav_order': 2,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_AG_SM_Mineral_fertilizer_import_Nmix.md',
  'title': 'Mineral Fertilizer Import',
  'nav_order': 3,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_AT_AT_Atmospheric_inflow_OXN.md',
  'title': 'Atmospheric Inflow (Oxidized N)',
  'nav_order': 4,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_AT_AT_Atmospheric_inflow_RDN.md',
  'title': 'Atmospheric Inflow (Reduced N)',
  'nav_order': 5,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_EF_EC_Fuel_import_Nmix.md',
  'title': 'Fuel Import',
  'nav_order': 6,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_EF_TR_Import_of_transport_fuel_Nmix.md',
  'title': 'Transport Fuel Import',
  'nav_order': 7,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_HY_AC_Aquaculture_feed_import_Nmix.md',
  'title': 'Aquaculture Feed Import',
  'nav_order': 8,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_MP_FP_Food_import_Nmix.md',
  'title': 'Food Import',
  'nav_order': 9,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_MP_OP_Ammonia_import__Nmix.md',
  'title': 'Ammonia Import',
  'nav_order': 10,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_MP_OP_Other_goods_import__Nmix.md',
  'title': 'Other Goods Import',
  'nav_order': 11,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'flow_RW_RW_PR_SO_Solid_waste_import_Nmix.md',
  'title': 'Solid Waste Import',
  'nav_order': 12,
  'parent': 'Rest of the world (RW)',
  'kind': 'flow'},
 {'folder': 'rest_of_the_world_pool',
  'file': 'pool_rest_of_the_world.md',
  'title': 'Rest of the world (RW)',
  'nav_order': 10,
  'has_children': True,
  'kind': 'pool',
  'balance': 'RW',
  'intro': '# Pool: Rest of the world (RW)\n'
           '\n'
           'This section contains all documented nitrogen inflows and transfers originating from the Rest of the world '
           '(RW) pool. Click on the individual sub-flows in the left-hand menu to view graphs and methodological '
           'explanations.\n'
           '\n'
           '{BALANCE}\n'}]
